### ISSUE TITLE
Doesn't work for 9 Pie

### ISSUE THREAD

**Issue by Sowkai24** [Scratch-Client-4/mobile#1]

**Comment by Hexsphere** [comment]
no description...?

**Comment by Sowkai24** [comment]
Hold on, I have a screenshot but insanely hard to upload from mobile app

**Comment by Hexsphere** [comment]
ah okay

**Comment by Sowkai24** [comment]
![Screenshot_20200418-145024](https://user-images.githubusercontent.com/62969951/79672265-37802580-8185-11ea-9b9f-dc6f72d1fb6a.png)

**Comment by micahlt** [comment]
All right, thanks!  Try updating the app by downloading the [latest version](https://build.phonegap.com/apps/3916109/share) from PhoneGap.  I fixed this in version 0.3.2.

**Comment by micahlt** [comment]
@Hexsphere fixed it :+1:

**Comment by Hexsphere** [comment]
cool
