### ISSUE TITLE
Future of SC4

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#13]
Yo, so I'm trying to rebuild SC4 with Ionic and Vue, and I'm nearly dead.  Any help (develop on the `ionic` branch of this repo) will help my sanity, thanks.

**Comment by micahlt** [comment]
@Scratch-Client-4/everyone Errr...

**Comment by locness3** [comment]
To use Vue with Parcel, you have to create an App.vue component which is your main thingy. Then you need to import it in the main script, and use `render` when initiating the vue instance to render it. See this as an example : https://github.com/ammezie/vue-parcel

**Comment by micahlt** [comment]
@locness3 At this point I'm debating whether or not we should even use Vue for the mobile app, as it's mainly just another dependency that could be avoided and no one on the team really knows a ton about it...

**Comment by locness3** [comment]
I think the best thing to do is to ditch Parcel, and use Vue "as-is". I have only got into trouble with Parcel. Or swicth to Webpack which seems to be better.

**Comment by micahlt** [comment]
@locness3 But we're using Sass, so we've got to have a bundler.  Parcel's website says that Webpack is slower and I _know_ it's way more complicated.  Do you have experience with it?

**Comment by locness3** [comment]
In fact, no. But do we really _need_ a bundler ? Can't we just setup node-sass or any SASS CLI, and make the html point to where it outputs the files?

**Comment by smileycreations15** [comment]
i used parcel before iirc

**Comment by locness3** [comment]
(we should still use npm for package management tho)

**Comment by smileycreations15** [comment]
(yas)

**Comment by micahlt** [comment]
@locness3 True, npm is my savior.

**Comment by micahlt** [comment]
Cool, closing this issue.  We'll use `node-sass` to interpret SCSS files and get rid of Parcel.  Also either one of you (@smileycreations15 @locness3) able to help build some?

**Comment by locness3** [comment]
> Also are either one of you (@smileycreations15 @locness3) able to help build some?

Sorry, wdym?

**Comment by micahlt** [comment]
Sorry, I mean after we choose a framework (we might be switching... again) could you guys help build in some features?

**Comment by locness3** [comment]
I hope I can. Although, if we don't use a bundler, problem is, we can't cleanly split stuff over multiple files...

**Comment by micahlt** [comment]
@locness3 True... though we shouldn't need much styling if we use a framework like Material Components.  And we can always import JS modules with ES6.

**Comment by locness3** [comment]
Yeah.

**Comment by locness3** [comment]
@micahlt

**Comment by micahlt** [comment]
@locness3 I'm reviving this a little bit, but I'm currently not looking at revising the UI framework.

**Comment by locness3** [comment]
> I think the best thing to do is to ditch Parcel

I completely disagree with myself. Using a bundler is kind of essential in complex projects like this (and we're still kind of using it). We need to use it with our Vue stuff, though. The part 2 of [this video](https://www.youtube.com/watch?v=4deVCNJq3qc) pretty much explains it all. I think we can close this issue, now. We'll continue with Parcel, with our own UI components.
