### ISSUE TITLE
Migration to Apache Cordova

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#16]
I'd like to suggest that we migrate from Adobe PhoneGap to Apache Cordova as our app compiler.  While PhoneGap was based on Cordova technology, when the projects split Cordova became much more powerful as an open-source tool, and it has several benefits: 

- Better compilation, offline in the terminal (no more uploads and compressing)
- More supported FOSS community
- Easier plugin integration

I'd like this to begin as soon as possible, as it's critical to testing future versions of SC4.

**Comment by ForgottenProgramme** [comment]
Hey, @micahlt ! I'm new to open source and the tag says 'good first issue', would you please help me with solving this ?

**Comment by micahlt** [comment]
@ForgottenProgramme Hi there!  Are you familiar with NodeJS and using a terminal/command prompt interface?

**Comment by ForgottenProgramme** [comment]
@micahlt 
I can use a command prompt. 
I have heard of NodeJS, but haven't worked in it.

**Comment by locness3** [comment]
Taking on this!

**Comment by githubfan** [comment]
@micahlt would be appreciated if you could review the PR locness suggested. I know you said you would be getting a bit busy :)
