### ISSUE TITLE
SeEmS LeGIt?!!111!??!?!/1/1/

### ISSUE THREAD

**Issue by AyzansAlt** [Scratch-Client-4/mobile#18]
![image](https://user-images.githubusercontent.com/36968271/89801204-c09ddc80-db27-11ea-87c0-d95d0b18cd07.png)

**Comment by locness3** [comment]
@AyzansAlt Please don't write like that.

**Comment by locness3** [comment]
Also, what are you trying to say; are you doing a fork?

**Comment by AyzansAlt** [comment]
it says itchy when it needs to say SC4 or a veriation

**Comment by AyzansAlt** [comment]
oops

**Comment by locness3** [comment]
PhoneGap is not being used anymore anyways, so I think that's not an issue.

**Comment by locness3** [comment]
![Screen Shot 2020-08-11 at 10 23 22](https://user-images.githubusercontent.com/37651007/89874862-b8dc4780-dbbc-11ea-9b53-295bdbe92247.png)
wait a second

**Comment by locness3** [comment]
@micahlt Would be nice if you actually kept everyone up-to-date with what's happening

**Comment by micahlt** [comment]
@locness3 Okay, sorry, been busy and not many other peeps have been actively contributing.  Incro on Scratch has agreed to let us use his design mockups.  He is also making a mobile app for iOS and we're planning to release our apps as a unified platform, tentatively known as Itchy.  This will help prevent confusion cross-platform.  SC4 Mobile was never a very user-friendly name anyway 😉 However, to prevent developer confusion the app's internal name will continue to be SC4.

**Comment by locness3** [comment]
> not many other peeps have been actively contributing

True, but IMO that's not a reason for doing things at their discretion. SC4 has a community, that community has to be considered and kept informed so it can be helpful and lively. And also, I'm an admin ;)

**Comment by AyzansAlt** [comment]
ok, is there an application-to-join form or something?

**Comment by micahlt** [comment]
@locness3 You're very right.  I'm so sorry - I'll try to be more democratic in the future.  👍

**Comment by locness3** [comment]
> ok, is there an application-to-join form or something?

Just ask :)

**Comment by locness3** [comment]
> his design mockups. He is also making a mobile app for iOS

I'd like to know more about both ;) Also, instead of two Itch-ies, why not the same thing (this repo) for both iOS and Android? Incro would join SC4 then

**Comment by micahlt** [comment]
The functions of the apps will be virtually the same - however Incro's version is written in Swift.  I have a Figma link I can give you, but I don't have access to my desktop right now.

**Comment by locness3** [comment]
Incro's using Swift? Ok then.

**Comment by micahlt** [comment]
[This link](https://www.figma.com/file/Wf44u2WoQy66qkkMm3N3Ut/Scratch-Mobile-Concepts---Ekmand-Edition) should work if you're looking for the Figma page.

**Comment by AyzansAlt** [comment]
Okay, ty

**Comment by AyzansAlt** [comment]
:O

**Comment by locness3** [comment]
Sorry, we're keeping stuff clean ;)

**Comment by AyzansAlt** [comment]
O:
