### ISSUE TITLE
Fix dot-prop vulnerability

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#20]
There's a critical security vulnerability risk with a dependency of Cordova.  Just run `npm install` to check it out.  However, we need someone to manually fix it, as `npm audit fix` claims that there are breaking changes.

**Comment by locness3** [comment]
I'm nto sure these "breaking changes" would affect us, we're using like 1% of cordova's features

**Comment by micahlt** [comment]
Hm... and I can always revert if there's an issue, I guess.

**Comment by locness3** [comment]
You should just test before pushing, i think you have time to work on that since you're pretty active rn ;)

**Comment by micahlt** [comment]
I don't actually have time lol, but I'll squeeze it in.

**Comment by locness3** [comment]
I assume you have time because you keep on adding new stuff 🙃

**Comment by micahlt** [comment]
Lol I really shouldn't tho - this issue was fixed in 6c1ebe17d00024b749294f5b69a0c8df80c0543b, by the way.
