### ISSUE TITLE
Do not include cordova.js in the project files

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/mobile#22]
I had raised this on our Teams DM, and I'm posting it here so it can get more attention.

We shouldn't include the cordova.js file in our project files. It's a file supposed to be auto-generated by cordova when building the app. It is included here as a "workaround" to make sure Parcel doesn't complain about a non-existent script, but we definitely shouldn't do that.

Looking at https://github.com/parcel-bundler/parcel/issues/2398, we have two possibilities :  Either [add cordova.js as an entry point](https://github.com/parcel-bundler/parcel/issues/2398#issuecomment-503589730) or use [this plugin](https://github.com/stoically/parcel-plugin-html-externals) to mark external files.

I was unable to get both of those to work, so any help appreciated.

cc @micahlt @Hexsphere

**Comment by AyzansAlt** [comment]
I'd say plugin

**Comment by locness3** [comment]
I also think it's the best solution. Would be appreciated if someone could get it to work.

**Comment by locness3** [comment]
Also, please don't 👍 your own messages ;)

**Comment by micahlt** [comment]
Fixed in 6ae86c4.

**Comment by locness3** [comment]
Awesome, congrats Micah!
