### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by AyzansAlt** [Scratch-Client-4/mobile#24]
Shouldn't the scratch games open in turbowarp (with 60fps) /forkphorus in fullscreen without depending on scratch?

**Comment by locness3** [comment]
They will, but iirc viewing projects currently doesn't even work

**Comment by locness3** [comment]
They will, but iirc viewing projects currently doesn't even work

**Comment by locness3** [comment]
They will, but iirc viewing projects currently doesn't even work

**Comment by AyzansAlt** [comment]
forkphorous? (https://forkphorus.github.io/app.html?id=INSERT_ID_HERE

**Comment by locness3** [comment]
Possibly, but i think we would include the forkphorus code directly

**Comment by AyzansAlt** [comment]
ookay
