### ISSUE TITLE
building the apk

### ISSUE THREAD

**Issue by AyzansAlt** [Scratch-Client-4/mobile#26]
![image](https://user-images.githubusercontent.com/36968271/93759919-01970f80-fc03-11ea-95ac-431eef528a32.png)
line 26 @locness3

**Comment by locness3** [comment]
Make sure you have Java 8? Android builds are not my thing.

**Comment by AyzansAlt** [comment]
I play MC with Java 8 though?

**Comment by YOYITsM3M8** [comment]
The MC launcher has java 8 bundled in it

**Comment by YOYITsM3M8** [comment]
Not installed system wide

**Comment by locness3** [comment]
Yup, first install java 8

**Comment by AyzansAlt** [comment]
I'm an idiot
