### ISSUE TITLE
Should the repository be renamed?

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#28]
Now that Scratch Client 4 Mobile has been rebranded to the public as Itchy, should we rename this repository to Itchy as well?  It would make it easier for Scratchers to find as well as be more consistent.  I've personally never renamed a repo before, so I don't know the consequences (e.g., how long GitHub will keep a redirect going).

**Comment by locness3** [comment]
Seems like you can safely rename the repo, redirects are kept for long enough (if not forever). I'd name it `itchy-cordova` as a distinction from the swift version

**Comment by micahlt** [comment]
Sounds good!
