### ISSUE TITLE
Issues with bundling to PhoneGap

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#3]
When you use Parcel to bundle the assets (SCSS, Vue) the `index.html` file adds slashes to file paths to scripts, images, etc.  This causes the app when packaged with PhoneGap to be unstyled HTML without any functionality.  Currently this is avoided by removing slashes manually after building with Parcel.  Any help with this would be very convenient.

**Comment by micahlt** [comment]
@Hexsphere (I just assigned you because you have more Parcel experience than I do; no pressure)

**Comment by locness3** [comment]
If I understand right, it adds a slash to the beginning of their paths, and so they are fetched from the phone's filesystem's root?
Also, this may be why it looks like this for me :
![Screenshot_2020-05-08-17-26-36](https://user-images.githubusercontent.com/37651007/81421479-d5965880-9151-11ea-8d98-282a7b555146.png)
(may also be because of my outdated android, although I think phonegap uses its own webview, but i could be wrong, it could use the system's webview which is completely outdated)

**Comment by ConvexPolygon** [comment]
I'm on chromeos and I tested the .apk. It is horrible. Nothing works. I would recommend building it as a cached apk for cross-platform compatibility. Phonegap looks kind of outdated too, as my chromebook identifies it as an Android Lollipop package.

**Comment by micahlt** [comment]
@ConvexPolygon Nope, PhoneGap isn't out of date.  I do know some Chromebooks don't correctly run Android apps, so that might be it.  It's definitely not designed to work on a screen that big, as it's a mobile app, not a tablet app.  @locness3 Don't know why it's acting like that.  Could be an issue with Parcel, but I don't have my laptop at hand, so I'll have to fix it in about two days.

**Comment by micahlt** [comment]
@locness3 Latest version works for me... I'm running Marshmallow.  
![Screenshot_20200508-142930](https://user-images.githubusercontent.com/28816297/81451677-9ca6b580-914a-11ea-8985-3849244eba4c.png)

**Comment by micahlt** [comment]
Also @ConvexPolygon, what do you mean by cached APK?

**Comment by locness3** [comment]
@micahlt I really think it's my Android (4.4 KitKat lol)

**Comment by micahlt** [comment]
@locness3 lol KitKat, those were the days

**Comment by ConvexPolygon** [comment]
> Also @ConvexPolygon, what do you mean by cached APK?
I meant build it as a PWA and allow users to store the app in their cache.
My chromebook is running Android Oreo in a vm

**Comment by ConvexPolygon** [comment]
I also realized I didn't build it, that's the problem. I forgot to build parcel.

**Comment by ConvexPolygon** [comment]
> @locness3 lol KitKat, those were the days

Yes, I started with honeycomb on my tablet.

**Comment by locness3** [comment]
While we're at it saying our first android versions I started with Ice Cream Sandwich

**Comment by micahlt** [comment]
Closing this issue.  The current solution is to just go through and remove all slashes in front of file paths.  This includes `links`, `scripts`, and `imgs`.  Also, we're moving to Cordova - check out #16.

**Comment by locness3** [comment]
Isn't Cordova PhoneGap?
