### ISSUE TITLE
Help with opening projects

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#4]
I've built a large skeleton for this app, but I need some help with opening projects.  So far we're using Forkphorus, but it may not be the optimal method to use.  Suggestions?

**Comment by geographix** [comment]
@micahlt You should definitely switch from forkphorus because it can render graphics poorly. Maybe you could try the original embeded codes for scratch projects?

**Comment by micahlt** [comment]
@geographix Would you be able to add that and make a PR?  I've done a whole snap-ton of this myself and some help would be nice :smiley:

**Comment by geographix** [comment]
@micahlt Sure! Although I don't fully understand the principles of app building. Is it the same as building website: HTML, JS, CSS?

**Comment by micahlt** [comment]
Pretty much!

**Comment by geographix** [comment]
Cool! I'll work on it today!

**Comment by geographix** [comment]
Where's can I find the project viewing page?

**Comment by micahlt** [comment]
@geographix It's all in one page.  When you click a project, a `div` slides up and should show the project.

**Comment by geographix** [comment]
what's the class or id to identify it?

**Comment by micahlt** [comment]
@geographix it's class is `project-shade` and you should see a comment right before it that says: 
```html
<!-- User Info window ends here and project window starts -->
```

**Comment by geographix** [comment]
Great! I'll try and get it done if I can find some time...

**Comment by micahlt** [comment]
@geographix Thanks man.  Appreciate the help :+1:

**Comment by geographix** [comment]
No problemo

**Comment by YOYITsM3M8** [comment]
@geographix  can I help?

**Comment by geographix** [comment]
hmmm... maybe but this seems like a pretty basic bit of html.

**Comment by YOYITsM3M8** [comment]
Yeah

**Comment by geographix** [comment]
@micahlt I think I have managed to find the solution to your problem. See the PR!

**Comment by micahlt** [comment]
@geographix I think I actually found the problem and fixed it.  It's live with version 0.3.5!

**Comment by geographix** [comment]
What was it?

**Comment by micahlt** [comment]
I had to replace the Vue templating strings after a user closed the project
shade.  👍

**Comment by geographix** [comment]
Oh! :thumbsup:
