### ISSUE TITLE
Documentation needed!

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#6]
There needs to be more documentation for SC4 Mobile and in fact, all of the other SC4 repositories.  If anyone has some spare time, it'd be nice to go through and comment on the code so others can contribute.

**Comment by geographix** [comment]
I am not an official member but if I can find some time I'd be happy to help! 😄

**Comment by locness3** [comment]
If there was actual code in the desktop repos, I would

**Comment by micahlt** [comment]
@locness3 true lol
