### ISSUE TITLE
Switch to a more native-looking interface

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/mobile#7]
The current UI for SC4 Mobile is really cool, but I was wondering: would it be better to focus more on functionality and integration with the operating system?  If we wanted to aim for more uniformity with the OS we could use [the Ionic framework](https://ionicframework.com/) instead of custom styling.  Any thoughts, @Scratch-Client-4/everyone?  This is a big decision.

**Comment by 4meltdown4** [comment]
Hmmm, I would say we should work on integrating it with the OS even though I love the current UI

**Comment by locness3** [comment]
Yeah, I think OS integration would definitely be great.

**Comment by micahlt** [comment]
@4meltdown4 @locness3 So, switch to Ionic?

**Comment by locness3** [comment]
I would.

**Comment by micahlt** [comment]
All righty then.  We're switching to Ionic Components for the mobile app, which means I'll essentially have to reconstruct the HTML sections.  I'll make a PR in the next week or two.

**Comment by locness3** [comment]
@micahlt please read this first : https://github.com/Scratch-Client-4/mobile/issues/8#issuecomment-625942637

**Comment by Huelz** [comment]
I feel we should stick to the current look, as it might cause confusion on how to navigate the sight. Another possible app for the UI is Adobe XD, although some might not be able to buy or afford it. Although iconic components might be nice, keep in mind this is a kids website, and for (especially younger kids) it might be hard for them to use:

**Comment by micahlt** [comment]
SC4 Mobile is a native (downloadable) app, not a website.  We already are changing the look from Scratch.  In my opinion, being consistent with the OS makes it easier to navigate, not harder.  

I'm not sure why you brought up Adobe XD.  Can you explain further?

**Comment by locness3** [comment]
Adobe XD is a UI design software, it's not possible to build a functional UI with it (and btw it's free)

**Comment by locness3** [comment]
@micahlt So you stay with Ionic?

**Comment by micahlt** [comment]
@locness3 Yeah, I think we should. I've started building on the [`ionic` branch](https://github.com/Scratch-Client-4/mobile/tree/ionic).

**Comment by locness3** [comment]
okay.

**Comment by micahlt** [comment]
Hey, @Scratch-Client-4/everyone.  I'd like us to vote on a framework as I'm encountering a lot of issues building with Ionic.  I've set up a poll, so [please vote!](https://strawpoll.com/pg2swzzf/r)

**Comment by ConvexPolygon** [comment]
I'm doing a material design course right now, and I like it's framework. I'd do material design :)

**Comment by locness3** [comment]
Ionic Components doesn't support Vue, and we're going with our own components now.

**Comment by AyzansAlt** [comment]
I think we should just have a settings option, where we can toggle the look from these options:
- ios (native look)
- material (uhh)
- android (native look)

**Comment by locness3** [comment]
This involves extra coding and extra css libraries
